require('dotenv').config();
const { argv } = require('node:process');
const { Client } = require('pg');

const SQL = `
  DROP TABLE IF EXISTS game_developers, game_genres CASCADE;
  DROP TABLE IF EXISTS games, developers, genres CASCADE;

  CREATE TABLE IF NOT EXISTS games (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    steam_id INTEGER UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    release_date DATE,
    rating INTEGER,
    image TEXT,
    background TEXT
  );

  CREATE TABLE IF NOT EXISTS developers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE
  );

  CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE
  );

  CREATE TABLE IF NOT EXISTS game_developers (
    game_id INTEGER REFERENCES games(id) ON DELETE CASCADE,
    developer_id INTEGER REFERENCES developers(id) ON DELETE CASCADE,
    PRIMARY KEY (game_id, developer_id)
  );

  CREATE TABLE IF NOT EXISTS game_genres (
    game_id INTEGER REFERENCES games(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (game_id, genre_id)
  );
`;

const connectionString = argv[2] || process.env.DATABASE_URL;
const client = new Client({ 
  connectionString,
  ssl: connectionString.includes('localhost') ? false : { rejectUnauthorized: false }
});

function cleanText(text) {
  if (!text) return null;
  return text
    .replace(/<[^>]*>?/gm, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/\s\s+/g, ' ')
    .trim();
}

async function getGameIds() {
  try {
    const response = await fetch('https://steamspy.com/api.php?request=top100forever');
    const results = await response.json();
    let appIds = Object.keys(results);
    return appIds;
  } catch (error) {
    console.error(error);
  }
}

async function getSteamData() {
  try {
    const gameIds = await getGameIds();
    const games = [];
    console.log(`Starting fetch for ${gameIds.length} games...`);
    for (let i = 0; i < gameIds.length; i++) {
      const gameId = gameIds[i];
      const response = await fetch(`https://store.steampowered.com/api/appdetails?appids=${gameId}&l=english`);
      const result = await response.json();
      const appId = Object.keys(result)[0];
      if (result[appId].success) {
        const gameData = result[appId].data;
        const parsedDate = new Date(gameData.release_date.date);
        const finalDate = isNaN(parsedDate) 
          ? null 
          : parsedDate.toISOString().split('T')[0];
        const rating = gameData.metacritic 
          ? gameData.metacritic.score 
          : null;
        games.push({ 
          steam_id: gameData.steam_appid,
          name: gameData.name, 
          description: cleanText(
            gameData.short_description 
            || gameData.about_the_game 
            || ''
          ),
          release_date: finalDate,
          rating: rating,
          developers: gameData.developers,
          genres: gameData.genres,
          image: gameData.header_image,
          background: gameData.background,
        });
        console.log(`[${i + 1}/${gameIds.length}] Fetched: ${gameData.name}`);
      }
      await new Promise(resolve => setTimeout(resolve, 1500));
    }
    return games;
  } catch (error) {
    console.error(error);
  }
}

async function seed() {
  try {
    const games = await getSteamData();
    if (!games || games.length === 0) throw new Error("No games found.");
    console.log('Game data acquired.');
    await client.connect();
    await client.query("SET client_encoding TO 'UTF8'");
    await client.query('BEGIN');
    console.log('Seeding started...');
    await client.query(SQL);
    console.log('Tables created.');
    for (const game of games) {
      const gameRes = await client.query(
        `INSERT INTO games (
        steam_id, 
        name, 
        description, 
        release_date, 
        rating, 
        image, 
        background
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        ON CONFLICT (steam_id) DO UPDATE SET name = EXCLUDED.name 
        RETURNING id`,
        [
          game.steam_id, 
          game.name, 
          game.description, 
          game.release_date, 
          game.rating, 
          game.image, 
          game.background
        ]
      );
      const gameId = gameRes.rows[0].id;

      if (game.developers) {
        for (const devName of game.developers) {
          const devRes = await client.query(
            `INSERT INTO developers (name) VALUES ($1)
            ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
            RETURNING id`, [devName]
          );
          const devId = devRes.rows[0].id;

          await client.query(
            `INSERT INTO game_developers (game_id, developer_id) VALUES ($1, $2)
            ON CONFLICT DO NOTHING`, [gameId, devId]
          );
        }
      }

      if (game.genres) {
        for (const genreName of game.genres) {
          const genRes = await client.query(
            `INSERT INTO genres (name) VALUES ($1)
            ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
            RETURNING id`, [genreName.description]
          );
          const genId = genRes.rows[0].id;

          await client.query(
            `INSERT INTO game_genres (game_id, genre_id) VALUES ($1, $2)
            ON CONFLICT DO NOTHING`, [gameId, genId]
          );
        }
      }
    }
    await client.query('COMMIT');
    console.log('Seeding completed successfully.');
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Seeding failed. Rolling back: ', error);
  } finally {
    await client.end();
  }
}

seed();