require('dotenv').config();
const { argv } = require('node:process');
const { Client } = require('pg');

const SQL = `
  DROP TABLE IF EXISTS film_genres, film_cast, film_directors CASCADE;
  DROP TABLE IF EXISTS films, people, genres CASCADE;

  CREATE TABLE IF NOT EXISTS films (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    tmdb_id INTEGER UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    release_year INTEGER,
    imdb_url TEXT
  );

  CREATE TABLE IF NOT EXISTS people (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tmdb_id INTEGER UNIQUE,
    name TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS genres (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tmdb_id INTEGER UNIQUE,
    name TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS film_genres (
    film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
  );

  CREATE TABLE IF NOT EXISTS film_cast (
    film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    person_id INTEGER REFERENCES people(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, person_id)
  );

  CREATE TABLE IF NOT EXISTS film_directors (
    film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    person_id INTEGER REFERENCES people(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, person_id)
  );
`;

const client = new Client({ connectionString: argv[2] });

const options = {
  method: 'GET',
  headers: {
    accept: 'application/json',
    Authorization: `Bearer ${process.env.TMDB_ACCESS_TOKEN}`,
  }
};

async function seed() {
  await client.connect();
  await client.query("SET client_encoding TO 'UTF8'");
  try {
    await client.query('BEGIN');
    console.log('Seeding started...');
    await client.query(SQL);
    console.log('Tables created.');
    const genreRes = await fetch('https://api.themoviedb.org/3/genre/movie/list?language=en', options);
    const { genres: tmdbGenres } = await genreRes.json();
    const genreInternalIds = new Map();
    for (const g of tmdbGenres) {
      const res = await client.query(
        `INSERT INTO genres (tmdb_id, name) VALUES ($1, $2) RETURNING id`,
        [g.id, g.name]
      );
      genreInternalIds.set(g.id, res.rows[0].id);
    }
    console.log('Genres initialized. Fetching films...');

    for (let page = 1; page <= 5; page++) {
      const response = await fetch(`https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=${page}`, options);
      const { results } = await response.json();
      for (const movie of results) {
        const detailRes = await fetch(`https://api.themoviedb.org/3/movie/${movie.id}?language=en-US`, options);
        const detail = await detailRes.json();
        const imdbUrl = detail.imdb_id ? `https://www.imdb.com/${detail.imdb_id}` : null;
        const releaseYear = movie.release_date ? parseInt(movie.release_date.split('-')[0]) : null;

        const filmRes = await client.query(
          `INSERT INTO films (tmdb_id, title, description, release_year, imdb_url) 
           VALUES ($1, $2, $3, $4, $5) ON CONFLICT (tmdb_id) DO UPDATE SET title = EXCLUDED.title 
           RETURNING id`,
          [movie.id, movie.title, movie.overview, releaseYear, imdbUrl]
        );
        const filmId = filmRes.rows[0].id;

        for (const gid of movie.genre_ids) {
          const internalId = genreInternalIds.get(gid);
          await client.query(
            `INSERT INTO film_genres (film_id, genre_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`,
            [filmId, internalId]
          );
        }

        const creditRes = await fetch(`https://api.themoviedb.org/3/movie/${movie.id}/credits`, options);
        const { cast, crew } = await creditRes.json();

        for (const member of crew.filter(c => c.job === 'Director')) {
          const res = await client.query(
            'INSERT INTO people (tmdb_id, name) VALUES ($1, $2) ON CONFLICT (tmdb_id) DO UPDATE SET name = EXCLUDED.name RETURNING id',
            [member.id, member.name]
          );
          const pId = res.rows[0].id;
          await client.query('INSERT INTO film_directors (film_id, person_id) VALUES ($1, $2) ON CONFLICT DO NOTHING', [filmId, pId]);
        }

        for (const member of cast.slice(0, 5)) {
          const res = await client.query(
            'INSERT INTO people (tmdb_id, name) VALUES ($1, $2) ON CONFLICT (tmdb_id) DO UPDATE SET name = EXCLUDED.name RETURNING id',
            [member.id, member.name]
          );
          const pId = res.rows[0].id;
          await client.query('INSERT INTO film_cast (film_id, person_id) VALUES ($1, $2) ON CONFLICT DO NOTHING', [filmId, pId]);
        }
      }
    }
    await client.query('COMMIT');
    console.log('Seeding completed successfully.');
  } catch (error) {
    console.error('Seeding failed. Rolling back: ', error);
  } finally {
    await client.end();
  }
}

seed();
